<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Create Government Site' => 'Создание ссылки на сайт правительства',
    'Government Sites' => 'Сайты правительства',
    'Update' => 'Изменить',
    'Delete' => 'Удалить',
    'Search'=> 'Найти',
    'Reset' => 'Сбросить',
    'Update {modelClass}: ' => 'Внесите изменения {modelClass}: ',
    'Logout' => 'Выход',
    'Home' => 'Главная',
    'Change position' => 'Изменить позиции сайтов',
    'Move forward' => 'Вперед',
    'Partner Sites' => 'Сайты партнеров',
    'Create Partner Site' => 'Добавить новый сайт',
    'Create' => 'Добавить',
    'Government' => 'Правительство',
    'Partner' => 'Партнеры',
    'Site' => 'Сайты',
    'Login' => 'Войти',
    'Permit' => 'Доступы',
    'Role' => 'Роли',
    'Permission' => 'Парава',
    'You are not allowed. Contact your administrator.' => 'У вас недостаточно прав. Обратитесь к администратору.',
    'Incorrect username or password is incorrect.' => 'Не правильное имя пользователя или неверный пароль.',
    'Change user role' => 'Настроить права',
    'Create User' => 'Создать нового',
    'Users' => 'Пользователи',
    'User name' => 'Имя пользователя',
    'Email' => 'Электронная почта',
    'Date created' => 'Дата создания',
    'Holidays' => 'Праздники',
    'Are you sure you want to delete this item?' => 'Вы уверены что хотите удалить?',
    'Created At' => 'Создано',
    'Updated At' => 'Обновлено',
    'Created By' => 'Создал',
    'Updated By' => 'Обновил',

    //Holidays block
    'Slug' => 'Ссылка на объект',
    'Name Holiday' => 'Праздник',
    'Text Holiday' => 'Описание праздника',
    'Date Holiday' => 'День праздника',
    'Logo Holiday' => 'Логотип праздника',
    'Status Holiday' => 'Показывать праздник',
    'Logo Holiday Update' => 'Логотип праздника',
    'Create Holidays' => 'Добавить праздник'
];
